name: update-charts
on:
  schedule:
    - cron:  '0 0 * * *'
  workflow_dispatch: {}
permissions:
  contents: write
jobs:
  update-charts:
    runs-on: ubuntu-latest
    steps:
      - name: Install Nix
        uses: cachix/install-nix-action@v20
        with:
          extra_nix_config: 'experimental-features = nix-command flakes'
      - name: Check for updates
        run: nix run .#helmupdater.x86_64-linux update-all --commit
      - name: Push updates
        run: git push
